ALTER TABLE ITEM_MUSICIAN DROP FOREIGN KEY FK_ITEM_MUSICIAN_musicians_ID
ALTER TABLE ITEM_MUSICIAN DROP FOREIGN KEY FK_ITEM_MUSICIAN_CD_ID
DROP TABLE ITEM
DROP TABLE MUSICIAN
DROP TABLE ITEM_MUSICIAN
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
